-- Chronos · AI 长期记忆表(Supabase 免费版)
-- 在 Supabase 控制台 SQL Editor 里执行本文件。
-- 使用 anon key + RLS(个人工具场景;如需更严可换 authenticated)。

create table if not exists public.memories (
  id bigint generated by default as identity primary key,
  kind text not null,              -- profile / fact / summary
  content text not null,
  source text not null default 'manual',
  created_at timestamptz not null default now()
);

alter table public.memories enable row level security;

-- 允许匿名插入(app 内 anon key 写入)
create policy "memories_anon_insert" on public.memories
  for insert with check (true);

-- 允许匿名读取(跨设备同步时 app 可拉取)
create policy "memories_anon_select" on public.memories
  for select using (true);
